# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protobufs import model_pb2 as protobufs_dot_model__pb2


class ModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Encoder = channel.unary_unary(
                '/model.Model/Encoder',
                request_serializer=protobufs_dot_model__pb2.EncoderRequest.SerializeToString,
                response_deserializer=protobufs_dot_model__pb2.EncoderResponse.FromString,
                )
        self.Decoder = channel.unary_unary(
                '/model.Model/Decoder',
                request_serializer=protobufs_dot_model__pb2.Empty.SerializeToString,
                response_deserializer=protobufs_dot_model__pb2.DecoderResponse.FromString,
                )
        self.Eval = channel.unary_unary(
                '/model.Model/Eval',
                request_serializer=protobufs_dot_model__pb2.EvalRequest.SerializeToString,
                response_deserializer=protobufs_dot_model__pb2.EvalResponse.FromString,
                )
        self.CreatePrediction = channel.unary_unary(
                '/model.Model/CreatePrediction',
                request_serializer=protobufs_dot_model__pb2.PredictRequest.SerializeToString,
                response_deserializer=protobufs_dot_model__pb2.Empty.FromString,
                )
        self.GetResult = channel.unary_unary(
                '/model.Model/GetResult',
                request_serializer=protobufs_dot_model__pb2.Empty.SerializeToString,
                response_deserializer=protobufs_dot_model__pb2.PredictResponse.FromString,
                )
        self.Config = channel.unary_unary(
                '/model.Model/Config',
                request_serializer=protobufs_dot_model__pb2.Empty.SerializeToString,
                response_deserializer=protobufs_dot_model__pb2.ConfigResponse.FromString,
                )


class ModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Encoder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decoder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Eval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePrediction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Config(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Encoder': grpc.unary_unary_rpc_method_handler(
                    servicer.Encoder,
                    request_deserializer=protobufs_dot_model__pb2.EncoderRequest.FromString,
                    response_serializer=protobufs_dot_model__pb2.EncoderResponse.SerializeToString,
            ),
            'Decoder': grpc.unary_unary_rpc_method_handler(
                    servicer.Decoder,
                    request_deserializer=protobufs_dot_model__pb2.Empty.FromString,
                    response_serializer=protobufs_dot_model__pb2.DecoderResponse.SerializeToString,
            ),
            'Eval': grpc.unary_unary_rpc_method_handler(
                    servicer.Eval,
                    request_deserializer=protobufs_dot_model__pb2.EvalRequest.FromString,
                    response_serializer=protobufs_dot_model__pb2.EvalResponse.SerializeToString,
            ),
            'CreatePrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePrediction,
                    request_deserializer=protobufs_dot_model__pb2.PredictRequest.FromString,
                    response_serializer=protobufs_dot_model__pb2.Empty.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=protobufs_dot_model__pb2.Empty.FromString,
                    response_serializer=protobufs_dot_model__pb2.PredictResponse.SerializeToString,
            ),
            'Config': grpc.unary_unary_rpc_method_handler(
                    servicer.Config,
                    request_deserializer=protobufs_dot_model__pb2.Empty.FromString,
                    response_serializer=protobufs_dot_model__pb2.ConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.Model', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Model(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Encoder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.Model/Encoder',
            protobufs_dot_model__pb2.EncoderRequest.SerializeToString,
            protobufs_dot_model__pb2.EncoderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Decoder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.Model/Decoder',
            protobufs_dot_model__pb2.Empty.SerializeToString,
            protobufs_dot_model__pb2.DecoderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Eval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.Model/Eval',
            protobufs_dot_model__pb2.EvalRequest.SerializeToString,
            protobufs_dot_model__pb2.EvalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.Model/CreatePrediction',
            protobufs_dot_model__pb2.PredictRequest.SerializeToString,
            protobufs_dot_model__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.Model/GetResult',
            protobufs_dot_model__pb2.Empty.SerializeToString,
            protobufs_dot_model__pb2.PredictResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Config(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.Model/Config',
            protobufs_dot_model__pb2.Empty.SerializeToString,
            protobufs_dot_model__pb2.ConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
