# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/strategy_args.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprotobufs/strategy_args.proto\x12\rstrategy.args\"M\n\x0cPunishTokens\x12\x0f\n\x07scaling\x18\x01 \x01(\x01\x12\x16\n\x0e\x63omment_tokens\x18\x02 \x03(\x03\x12\x14\n\x0cspace_tokens\x18\x03 \x03(\x03\x42\x10Z\x0e/strategy/argsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobufs.strategy_args_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\016/strategy/args'
  _globals['_PUNISHTOKENS']._serialized_start=48
  _globals['_PUNISHTOKENS']._serialized_end=125
# @@protoc_insertion_point(module_scope)
